import Head from "next/head";

import Header from "../components/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>devjobs</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/assets/favicon-32x32.png' />
      </Head>
      <Header />
      <main></main>
    </div>
  );
}
