import React, { useState, useEffect, useCallback } from "react";
import Head from "next/head";
import Banner from "../../components/Banner";
import Header from "../../components/Header";
import Jobs from "../../public/data.json";
import JobTitleBar from "../../components/JobTitleBar";

import JobDescription from "../../components/JobDescription";
import JobFooter from "../../components/JobFooter";

const Page = (props) => {
  return (
    <div className='flex h-screen flex-col'>
      <div className='bg-lightgray transition-colors duration-300 ease-in-out dark:bg-midnight'>
        <Head>
          <title>{`devjobs - ${props.projectData.company}`}</title>
          <meta name='description' content='Generated by create next app' />
          <meta name='theme-color' content='#5964E0' />
          <link rel='icon' href='/assets/favicon-32x32.png' />
        </Head>
        <Banner />
        <Header />
        {/* JOB SPECIFIC TITLE BAR */}
        <JobTitleBar data={props.projectData} />
        {/* JOB SPECIFIC DESCRIPTION */}
        <JobDescription data={props.projectData} />
        {/* JOB SPECIFIC FOOTER */}
      </div>
      <div className='w-full flex-auto bg-lightgray transition-colors duration-300 ease-in-out dark:bg-midnight'></div>
      <JobFooter data={props.projectData} />
    </div>
  );
};

export default Page;

export async function getStaticPaths() {
  const paths = Jobs.map((post) => ({
    params: { jobId: post.id.toString() },
  }));

  return {
    fallback: false,
    paths,
  };
}

export async function getStaticProps(context) {
  const jobId = context.params.jobId;

  const selectedProject = Jobs.find(({ id }) => id == jobId);

  return {
    props: {
      projectData: selectedProject,
    },
  };
}
