import React, { useState, useEffect, useCallback } from "react";
import Head from "next/head";
import Banner from "../../components/Banner";
import Header from "../../components/Header";
import Jobs from "../../public/data.json";
import JobTitleBar from "../../components/JobTitleBar";

const Page = (props) => {
  return (
    <div className={` flex h-screen flex-col`}>
      <div className='bg-lightgray transition-colors duration-300 ease-in-out dark:bg-midnight'>
        <Head>
          <title>devjobs</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/assets/favicon-32x32.png' />
        </Head>

        <Banner />
        <Header />
        <JobTitleBar data={props.projectData} />

        {/* SEARCH RESULTS */}
        <main className='mx-auto mt-6 max-w-[810px] px-6 md:px-10'>
          <div className='rounded-md bg-white p-6'>
            <p className='text-darkgray'>{props.projectData.description}</p>
          </div>
        </main>
      </div>
      <div className='flex-auto bg-lightgray transition-colors duration-300 ease-in-out dark:bg-midnight'></div>
    </div>
  );
};

export default Page;

export async function getStaticPaths() {
  const paths = Jobs.map((post) => ({
    params: { jobId: post.id.toString() },
  }));

  return {
    fallback: false,
    paths,
  };
}

export async function getStaticProps(context) {
  const jobId = context.params.jobId;

  const selectedProject = Jobs.find(({ id }) => id == jobId);

  return {
    props: {
      projectData: selectedProject,
    },
  };
}
